version: "3.9"
services:
  build: .
  ports:
    - "8000:80"
  depends_on:
    - db
  environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ConnectionStrings__DefaultConnection=Server=localhost\\MYSERVER;Database=Starbucks;User Id=josejesus;Password=5f6g7h8j9k01.;
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - PASS=5f6g7h8j9k01.
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
volumes: 
  mssqldata:
    driver: local
